// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        //agp_version = '7.2'
        //agp_version = '4.1.0'

        //agp_version = '8.3.1'

        //agp_version1 = '8.10.1'
        agp_version = '8.6.0'
        agp_version1 = '8.10.1'
        agp_version2 = agp_version1
    }
    repositories {
        //jcenter()
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$agp_version2"
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
        //classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.6'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        //jcenter()
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
